//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Description { get; set; }
        public string BookAuthor { get; set; }
        public string BookStatus { get; set; }
        public string BookPosition { get; set; }
        public string Publisher { get; set; }
        public string ISBN { get; set; }
        public string Language { get; set; }
        public string Date { get; set; }
        public string CopyRights { get; set; }
        public string Source { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string FileUpLoad { get; set; }
        public string BookImage { get; set; }
        public Nullable<int> ViewTotal { get; set; }

        public HttpPostedFileBase UploadFile { get; set; }
        public HttpPostedFileBase UploadImage { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
