//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TranId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string TranStatus { get; set; }
        public string TranDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TranDate_Accepted { get; set; }
        public string TranDate_Returned { get; set; }
        public string TranDate_AccReturned { get; set; }
        public string TranDate_Get { get; set; }
        public string TranDate_GiveBack { get; set; }
        public string TranDate_DeleteRequest { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
